# Railway Nixpacks configuration for Next.js SSR

[phases.setup]
# Install Node.js 20 LTS
nixPkgs = ["nodejs_20"]

[phases.install]
# Install dependencies without cache issues
cmds = [
  "npm ci"
]

[phases.build]
# Build the Next.js application
cmds = [
  "npm run build"
]

[start]
# Start the production server
cmd = "npm start"

[variables]
# Disable caching to avoid conflicts
CI = "true"
NODE_ENV = "production"
